openapi: 3.0.0
info:
  title: 과외 관리 서비스 API
  description: 선생님과 학생을 위한 과외 일정 관리 및 학습 자료 공유 플랫폼 API
  version: 1.0.0
  contact:
    name: Tutor Management Service
    email: tutor@example.com

servers:
  - url: http://localhost:3002/api/v1
    description: 개발 서버

tags:
  - name: 인증
    description: 사용자 로그인 및 회원가입 관련 API
  - name: 선생님
    description: 선생님 전용 API
  - name: 학생
    description: 학생 전용 API
  - name: 공용
    description: 공통 기능 API (캘린더, 게시판 등)

paths:
  /auth/login:
    post:
      tags:
        - 인증
      summary: 로그인
      description: 전화번호, 비밀번호, 역할로 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone_number
                - password
                - role
              properties:
                phone_number:
                  type: string
                  example: "010-1111-1111"
                password:
                  type: string
                  example: "1111"
                role:
                  type: string
                  enum: [teacher, student]
                  example: "teacher"
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/signup:
    post:
      tags:
        - 인증
      summary: 회원가입
      description: 새 사용자 계정 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phone_number
                - password
                - confirm_password
                - role
              properties:
                name:
                  type: string
                  example: "김과외"
                phone_number:
                  type: string
                  example: "010-1111-1111"
                password:
                  type: string
                  example: "1111"
                confirm_password:
                  type: string
                  example: "1111"
                role:
                  type: string
                  enum: [teacher, student]
                  example: "teacher"
      responses:
        '200':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: 입력 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /teachers/{teacher_id}/home:
    get:
      tags:
        - 선생님
      summary: 선생님 홈 화면 데이터 조회
      description: 오늘 날짜 기준으로 선생님의 오늘 수업 목록 조회
      parameters:
        - name: teacher_id
          in: path
          required: true
          schema:
            type: integer
          description: 선생님 ID
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/calendar:
    get:
      tags:
        - 선생님
      summary: 선생님 캘린더 조회
      description: 현재 월 기준으로 수업 통계 및 일정 조회
      parameters:
        - name: teacher_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/subjects:
    get:
      tags:
        - 선생님
      summary: 과목 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
    post:
      tags:
        - 선생님
      summary: 과목 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [subject, content]
              properties:
                subject:
                  type: string
                  example: "수학"
                content:
                  type: string
                  example: "중1 수학"
      responses:
        '200':
          description: 과목 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/subjects/{subject_id}:
    delete:
      tags:
        - 선생님
      summary: 과목 삭제
      parameters:
        - name: subject_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 과목 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/students:
    get:
      tags:
        - 선생님
      summary: 학생 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
    post:
      tags:
        - 선생님
      summary: 학생 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, phone_number, subject]
              properties:
                name:
                  type: string
                  example: "박학생"
                phone_number:
                  type: string
                  example: "010-4444-4444"
                subject:
                  type: string
                  example: "과학"
      responses:
        '200':
          description: 학생 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/students/{student_id}:
    delete:
      tags:
        - 선생님
      summary: 학생 삭제
      parameters:
        - name: student_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 학생 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/lessons:
    get:
      tags:
        - 선생님
      summary: 수업 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
    post:
      tags:
        - 선생님
      summary: 수업 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [student_id, class_date, class_time]
              properties:
                student_id:
                  type: integer
                  example: 1
                class_date:
                  type: string
                  format: date
                  example: "2025-10-31"
                class_time:
                  type: string
                  format: time
                  example: "14:00:00"
      responses:
        '200':
          description: 수업 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/lessons/{lesson_id}:
    delete:
      tags:
        - 선생님
      summary: 수업 삭제
      parameters:
        - name: lesson_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 수업 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/posts:
    get:
      tags:
        - 선생님
      summary: 게시글 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /teachers/{teacher_id}/posts/{post_id}:
    delete:
      tags:
        - 선생님
      summary: 게시글 삭제
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 게시글 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

    post:
      tags:
        - 선생님
      summary: 게시글 작성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [subject, title, content]
              properties:
                subject:
                  type: string
                  example: "수학"
                title:
                  type: string
                  example: "3차방정식 정리"
                content:
                  type: string
                  example: "미지수가 1개이고 차수가 3인 방정식이다."
      responses:
        '200':
          description: 게시글 작성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /students/{student_id}/home:
    get:
      tags:
        - 학생
      summary: 학생 홈 화면 데이터 조회
      description: 오늘 날짜 기준 수업 및 학습자료 조회
      parameters:
        - name: student_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /students/{student_id}/calendar:
    get:
      tags:
        - 학생
      summary: 학생 캘린더 조회
      parameters:
        - name: student_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /students/{student_id}/boards:
    get:
      tags:
        - 학생
      summary: 학생이 열람 가능한 게시글 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

components:
  schemas:
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "요청이 성공적으로 처리되었습니다."
        data:
          type: object
          nullable: true

    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            success:
              example: false
            error:
              type: string
              example: "에러 메시지"

    UserBase:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone_number:
          type: string
        role:
          type: string
          enum: [teacher, student]

    Teacher:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            subjects:
              type: array
              items:
                $ref: '#/components/schemas/Subject'

    Student:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            teacher_id:
              type: integer
            subject:
              type: string

    Subject:
      type: object
      properties:
        id:
          type: integer
        teacher_id:
          type: integer
        subject:
          type: string
        content:
          type: string

    Lesson:
      type: object
      properties:
        id:
          type: integer
        subject:
          type: string
        student_name:
          type: string
        time:
          type: string
          format: time
        date:
          type: string
          format: date

    Board:
      type: object
      properties:
        id:
          type: integer
        teacher_id:
          type: integer
        subject:
          type: string
        title:
          type: string
        content:
          type: string
        date:
          type: string
          format: date

    CalendarStats:
      type: object
      properties:
        subjects:
          type: integer
        total:
          type: integer
        completed:
          type: integer
        scheduled:
          type: integer
